# Generated by Django 5.1.1 on 2024-11-20 23:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_colecao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colecao',
            name='colecionador',
        ),
        migrations.RemoveField(
            model_name='colecao',
            name='livros',
        ),
        migrations.AddField(
            model_name='colecao',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='colecao',
            name='descricao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='colecao',
            name='nome',
            field=models.CharField(max_length=255),
        ),
    ]
