# Generated by Django 5.1.1 on 2024-11-21 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_colecao_colecionador_remove_colecao_livros_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colecao',
            name='usuario',
        ),
        migrations.AddField(
            model_name='colecao',
            name='colecionador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='colecoes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='colecao',
            name='livros',
            field=models.ManyToManyField(related_name='colecoes', to='core.livro'),
        ),
        migrations.AlterField(
            model_name='colecao',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='colecao',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
